name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --junitxml=report.xml
      continue-on-error: true

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: junitroei
        path: report.xml

    - name: Create test annotations
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: report.xml
